### ISSUE TITLE
[Bug]자동로그인 ->주문 상세 버그

### ISSUE THREAD

**Issue by wktkdandp** [APPSCHOOL2-Android/FinalProject-ShoppingMallService-team3#118]
## Description
자동로그인 으로 로그인 한 후에 주문 상세 페이지로 넘어가려고 하면 오류가 납니다.
발동 조건을 모르겠습니다. 어느 경우에는 주문 상세 페이지가 잘 나오는데 가끔 튕기네요.

java.lang.NullPointerException
at com.petpal.swimmer_customer.ui.order.OrderDetailFragment$ItemRecyclerViewAdapter.getItemCount(OrderDetailFragment.kt:152)

**Comment by gayeon00** [comment]
아마 order의 itemList가 세팅이 안된 상태에서 넘어가서 그런 것 같습니다.
